# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 59e27f8154bb5744a0e58b3395c1a9b86c1e49ba90efae63451e3368d0b03486d25a8f2cce6dc7ceb9a90cc2bf333432c7b58a3c71da12f2c93f34aa4e3e72aa

test:
  secret_key_base: 1ba89fd09be3e7496887ed6f514f7e90280410153467e5a0142ff6297ab47bd30c9daae999ac85c6c5184ad8f5af7da6a706fd05456b15cd105e165acd3e5095

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
